#!/usr/bin/env bash
# ClipAI: explain architecture — Next.js, Python backend, Workers
set -e
cd /home/je3393/clipai

echo "╔══════════════════════════════════════════════════╗"
echo "║           CLIPAI — Architecture Overview        ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""

echo "═══ 1. NEXT.JS (Frontend + API Routes) — port 3000 ═══"
echo ""
echo "  src/app/               # App Router pages"
echo "   ├── layout.tsx        # Root layout (next-themes provider)"
echo "   ├── middleware.ts     # Auth guard, redirects"
echo "   ├── auth/            # Login / signup / forgot-password"
echo "   ├── clipper/         # ⭐ Main UI: input YT URL, pick quality, generate"
echo "   ├── dashboard/       # User dashboard + proyek list"
echo "   ├── pricing/        # Pricing page (Tripay integration)"
echo "   └── api/             # API Routes (Next.js backend)"
echo "        ├── auth/       # NextAuth + custom signup/owner-login"
echo "        ├── clips/"
echo "        │   ├── generate/route.ts   # POST: validate token → call Python"
echo "        │   ├── progress/route.ts   # Webhook receiver from Python"
echo "        │   ├── status/route.ts     # Polling endpoint (3s interval)"
echo "        │   └── [id]/route.ts       # CRUD per clip"
echo "        ├── payments/   # Tripay create/callback/webhook/grant"
echo "        ├── admin/      # Owner-level user management"
echo "        ├── share/      # Public clip sharing"
echo "        ├── caption/    # Caption CRUD"
echo "        ├── feedback/   # User feedback"
echo "        └── download/   # Clip download"
echo ""
echo "  src/components/        # React components"
echo "   ├── Navbar.tsx        # Navigation + theme toggle"
echo "   ├── clip/            # ClipCard, ClipGrid, ShareModal, CaptionModal"
echo "   ├── ui/              # GenerateButton, ProcessingCard"
echo "   ├── ThemeToggle.tsx  # Dark mode toggle"
echo "   └── Feedback*.tsx    # Floating feedback widget"
echo ""
echo "  src/lib/               # Utilities"
echo "   ├── prisma.ts         # Prisma client singleton"
echo "   ├── plan.ts           # Plan expiry logic, token checks"
echo "   └── tripay.ts         # Tripay payment gateway helper"
echo ""
echo "  prisma/schema.prisma   # DB models: User, Project, Clip, Payment"
echo "  next.config.js          # allowedDevOrigins: clipai.toolje.my.id"
echo "  Tailwind CSS v4         # @custom-variant dark, next-themes"
echo ""

echo "═══ 2. PYTHON BACKEND (FastAPI) — port 8000 ═══"
echo ""
echo "  python-backend/"
echo "   ├── main.py           # ⭐ FastAPI app (222 lines)"
echo "   │   POST /process     # yt-dlp → ffmpeg → AssemblyAI → GPT →"
echo "   │                     # ffmpeg cut clips → upload R2 → return URLs"
echo "   │   POST /progress    # Update progress ke Next.js API"
echo "   ├── face_tracker.py   # OpenCV FaceDetectorYN (YuNet)"
echo "   ├── reframe.py        # Reframe clips for portrait/landscape"
echo "   ├── integration_example.py"
echo "   ├── models/           # Face detection models"
echo "   └── requirements.txt  # fastapi, uvicorn, openai, yt-dlp, boto3"
echo ""
echo "  PIPELINE FLOW:"
echo "  1) yt-dlp downloads video dari YouTube URL"
echo "  2) ffmpeg extracts audio → AssemblyAI transkrip"
echo "  3) GPT (via chenzk.top) generates clip timestamps dari transkrip"
echo "  4) ffmpeg cuts clips based on timestamps"
echo "  5) OpenCV face tracking (optional: portrait reframe)"
echo "  6) Upload clips ke Cloudflare R2"
echo "  7) POST progress ke Next.js /api/clips/progress"
echo "  8) Return r2Urls ke caller"
echo ""

echo "═══ 3. WORKERS (BullMQ + Redis) ═══"
echo ""
echo "  src/workers/"
echo "   └── clipWorker.ts     # BullMQ worker (75 lines)"
echo ""
echo "  FLOW:"
echo "  - Worker listens on queue 'clip-jobs' via Redis"
echo "  - Job data: { projectId, youtubeUrl }"
echo "  - Update Project status: QUEUED → PROCESSING → DONE/FAILED"
echo "  - Forward ke Python backend POST /process"
echo "  - Simpan hasil clips ke DB via Prisma"
echo ""
echo "  RUN: npm run worker    # npx tsx src/workers/clipWorker.ts"
echo ""


echo "═══ ARCHITECTURE DIAGRAM ═══"
echo ""
echo "  ┌───────────┐     HTTP      ┌──────────────┐"
echo "  │  Browser  │ ◄──────────►  │  Next.js 16   │"
echo "  │ (Telegram)│   tunnel:     │  :3000         │"
echo "  │           │ clipai.toolje │  + API Routes  │"
echo "  └───────────┘  .my.id       └───────┬────────┘"
echo "                                       │ POST /process"
echo "                                       ▼"
echo "  ┌───────────┐     BullMQ     ┌──────────────┐"
echo "  │  Redis     │ ◄──────────►  │  Worker       │"
echo "  │  (jobs)    │               │  clipWorker.ts│"
echo "  └───────────┘               └───────┬────────┘"
echo "                                       │ HTTP POST"
echo "                                       ▼"
echo "  ┌───────────┐     yt-dlp     ┌──────────────┐"
echo "  │ YouTube    │ ◄──────────── │  Python       │"
echo "  │            │   ffmpeg      │  FastAPI :8000│"
echo "  └───────────┘   AssemblyAI   │  + R2 upload   │"
echo "                    GPT         └──────┬───────┘"
echo "                                       │"
echo "                                       ▼"
echo "                               ┌──────────────┐"
echo "                               │  Cloudflare   │"
echo "                               │  R2 Storage   │"
echo "                               └──────────────┘"
echo ""

echo "═══════════════════════════════════════════════════"
echo "  START SERVICES:"
echo "    Next.js     →  npm run dev"
echo "    Python      →  cd python-backend && python3 -m uvicorn main:app --host 0.0.0.0 --port 8000"
echo "    Worker      →  npm run worker"
echo "    All-in-one  →  bash start-clipai.sh"
echo "═══════════════════════════════════════════════════"
